services:
  - type: web
    name: resolvit-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://www.resolvit-ai.online,https://resolvit-care-ai-powered-smart-resource-allocation-naoaaoakp.vercel.app
      - key: APP_DEBUG
        value: "false"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: AUTH0_DOMAIN
        value: resolvitai.us.auth0.com
      - key: AUTH0_CLIENT_ID
        value: ygoYS6OsQUiCqkGB6Bhrr56G0JP4c5qF
      - key: AUTH0_AUDIENCE
        value: https://resolvit-care-ai-powered-smart-resource-allocation-naoaaoakp.vercel.app
