export const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "http://127.0.0.1:8000";
export const API_BASE = `${BACKEND_URL}/api`;

export const ROLES = {
  ADMIN: "ADMIN",
  NGO_ADMIN: "NGO_ADMIN",
  FIELD_COORDINATOR: "FIELD_COORDINATOR",
  FIELD_OFFICER: "FIELD_OFFICER",
  VOLUNTEER: "VOLUNTEER",
  CITIZEN: "CITIZEN",
};
